doctrine_mongodb:
    connections:
        default:
            server: '%env(resolve:MONGODB_URI)%'
            options: {}
    default_database: 'arcadia_db'
    document_managers:
        default:
            mappings:
                App:
                    is_bundle: false
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App
            metadata_cache_driver: array # array, service, apcu, memcached, redis
