vich_uploader:
    db_driver: orm # ou 'mongodb' ou 'phpcr' ou 'propel'
    mappings:
        imgServices:
            uri_prefix: '/uploads/services'
            upload_destination: '%kernel.project_dir%/public/uploads/services'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
        imgHabitats:
            uri_prefix: 'uploads/habitats'
            upload_destination: '%kernel.project_dir%/public/uploads/habitats'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true
        imgAnimaux:
            uri_prefix: 'uploads/animaux'
            upload_destination: '%kernel.project_dir%/public/uploads/animaux'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
