vich_uploader:
    db_driver: orm # ou 'mongodb' ou 'phpcr' ou 'propel'
    mappings:
        product_image:
            uri_prefix: '/images/products'
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer