controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# post_register_redirect:
#     path: /register/redirect
#     controller: App\Controller\RegistrationController::redirectAfterRegistration  
verify_email:
    path: /admin/verify-email/{id}
    controller: App\Controller\Admin\Crud\UtilisateursCrudController::verifyEmail
    methods: [GET]
homepage:
    path: /
    controller: App\Controller\MainController::index