# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    # Redirection des utilisiteur connectés en fonction de leur Rôle
    # app.login_success_listener:
    #     class: App\EventListener\LoginSuccessListener
    #     arguments: ['@router', '@security.token_storage']
    #     tags:
    #         - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
    
    App\EventListener\LoginRedirectListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }